
####################################################################
# Loads default set of integrations. Do not remove.
default_config:


# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
#########################ATIVAR TTS GOOGLE HOME #################
tts:
  - platform: google_translate
    language: "pt-br"
#######################influxdb:##############################
influxdb:
  host: 192.168.100.3     # IP do servidor InfluxDB
  port: 8086
  database: hassio
  username: valmir
  password: 6394@NpyH
  max_retries: 3
  default_measurement: state
########################################################################