{
 "title": "Dashboard Valmir Home",
 "tags": [
  "home-assistant",
  "iot",
  "energia",
  "rede",
  "infra"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Potência Atual Casa  (W)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "W",
     "query": "SELECT last(\"value\") FROM \"W\" WHERE (\"entity_id\" = 'esp32_pzem_pzem_pot_ncia')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "entity_id::tag", "operator": "=", "value": "computadores_power" }
     ]
    }
   ]
  },
  {
   "title": "Energia Total Casa  (kWh)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "kWh",
     "query": "SELECT last(\"value\") FROM \"kWh\" WHERE (\"entity_id\" = 'esp32_pzem_pzem_energia_total')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id::tag", "operator": "=", "value": "dijuntor_electricity" }
     ]
    }
   ]
  },
  {
   "title": "Internet  Upload",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "measurement": "Mbit/s",
     "query": "SELECT last(\"value\") FROM \"W\" WHERE (\"entity_id\" = 'esp32_pzem_pzem_pot_ncia')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id::tag", "operator": "=", "value": "mikrotik_pppoe_out1_rx" }
     ]
    }
   ]
  },
  {
   "title": "Internet  Dowload",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "Mbit/s",
     "query": "SELECT last(\"value\") FROM \"W\" WHERE (\"entity_id\" = 'esp32_pzem_pzem_pot_ncia')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id::tag", "operator": "=", "value": "mikrotik_pppoe_out1_tx" }
     ]
    }
   ]
  },
  {
   "title": "Consumo Promox(w)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "W",
     "query": "SELECT last(\"value\") FROM \"W\" WHERE (\"entity_id\" = 'esp32_pzem_pzem_pot_ncia')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "entity_id::tag", "operator": "=", "value": "servidor_potencia" }
     ]
    }
   ]
  },
  {
   "title": "Energia Total  Proxmox (kWh)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "kWh",
     "query": "SELECT last(\"value\") FROM \"kWh\" WHERE (\"entity_id\" = 'esp32_pzem_pzem_energia_total')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "entity_id::tag", "operator": "=", "value": "servidor_electricity" }
     ]
    }
   ]
  },
  {
   "title": "Comsumo de Internet RX",
   "type": "timeseries",
   "description": "Comsumo de Internet",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 5 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "Mbit/s",
     "query": "SELECT mean(\"value\") FROM \"kB/s\" WHERE (\"entity_id\" =~ /homeassistant_.*(rx|tx).*/) GROUP BY time(1m) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id::tag", "operator": "=", "value": "mikrotik_pppoe_out1_rx" }
     ]
    }
   ]
  },
  {
   "title": "Conputador Power (w)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "W",
     "query": "SELECT last(\"value\") FROM \"W\" WHERE (\"entity_id\" = 'esp32_pzem_pzem_pot_ncia')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "entity_id::tag", "operator": "=", "value": "computadores_power" }
     ]
    }
   ]
  },
  {
   "title": "Corrente Total  Computador  (A)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "A",
     "query": "SELECT last(\"value\") FROM \"kWh\" WHERE (\"entity_id\" = 'esp32_pzem_pzem_energia_total')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Histórico de Potência Casa",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "W",
     "query": "SELECT mean(\"value\") FROM \"W\" WHERE (\"entity_id\" = 'esp32_pzem_pzem_pot_ncia') GROUP BY time(1m) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id::tag", "operator": "=", "value": "dijuntor_potencia" }
     ]
    }
   ]
  },
  {
   "title": "Comsumo de Internet TX",
   "type": "timeseries",
   "description": "Comsumo de Internet",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "Mbit/s",
     "query": "SELECT mean(\"value\") FROM \"kB/s\" WHERE (\"entity_id\" =~ /homeassistant_.*(rx|tx).*/) GROUP BY time(1m) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id::tag", "operator": "=", "value": "mikrotik_pppoe_out1_tx" }
     ]
    }
   ]
  }
 ]
}